### ISSUE TITLE
Add `ComingSoon` component to Gallery page

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#127]
### Add `ComingSoon` component to Gallery page

**Tasks:**

- [ ] Add `ComingSoon` component to the Gallery page
- [ ] Comment out other code so it does not render
- [ ] Verify functionality across different navbars
