### ISSUE TITLE
Implement sidebar for teacher's page

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#286]
# ✨ **Feature Description: Add Sidebar for Teacher's Page**

## Tasks
- [ ] Implement a **sidebar** for the Teacher's Page with **five distinct sections**, ensuring clear navigation.  
- [ ] Integrate **i18n** for multilingual support.  
- [ ] Add routings for sidebar sections to be displayed in the **navbar**.  

---

## 📎 **Additional Information**

[website plans](https://docs.google.com/presentation/d/1UHDjEPxilSh0wOhmLk_ywJ5yC372xF6Ivan3wNPlB0Q/edit?pli=1#slide=id.g31508db5e70_0_42)
### Visual Reference:  
![Sidebar Mockup](https://github.com/user-attachments/assets/d63cb5ef-68cf-45de-bdbb-c9e740d9def1)
