### ISSUE TITLE
update seo on static pages

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-WebPages#85]
### Tasks:

- [ ] Check every single static page (excluding dynamic pages such as clan pages for now) for existing SEO implementation.

- [ ] Update SEO metadata for each page to include essential social media tags:

  - [ ] **Open Graph (OG) Tags**:
    - `og:title`: The title of the page.
    - `og:description`: A brief description of the page.
    - `og:image`: The URL of an image representing the content.
    - `og:url`: The canonical URL of the page.

  - [ ] **Additional Meta Tags**:
    - `canonical`: The canonical URL of the page to avoid duplicate content issues.

- [ ] Ensure that each page has a unique and descriptive `title` , `description` and `keywords`  that align with the page content.

- [ ] Provide a brief summary of the updates made.

**Comment by Skoivumaki** [comment]
This issue is still highly wanted even though it is old, it still is relevant. Many static pages currently have some of these tags, but still need correction/review of their relevancy.
