### ISSUE TITLE
Enhance a Caption Component for team members

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-WebPages#89]
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/218caeaa-a5d0-457a-b7d0-abb4afe31dad">

### Tasks:

- [ ] **Create a new version of the component, call it v2**
- [ ] **Deprecate the existing implementation (v1)**:
  - Mark the current caption component implementation as deprecated.
  - Update documentation and code comments to indicate that v1 is no longer recommended.
- [ ] **Add a playbar to the caption component**:
  - Integrate a playbar to provide enhanced control and functionality.
- [ ] **Implement playbar positioning**:
  - Ensure the playbar is positioned with `sticky` or `fixed` positioning for user convenience.

- [ ] **Add control buttons**:
  - Include the following buttons on the playbar:
    - Play (existing implementation).
    - Pause.
    - Restart (start over).
    - Fullscreen/Exit.
  - Ensure these buttons are functional and visually consistent.

- [ ] **Add horizontal scrollbar**:
  - Integrate a horizontal scrollbar on the playbar similar to video players to allow users to navigate through the captions.

- [ ] **Implement fullscreen mode**:
  - Provide an option for fullscreen mode in the playbar.
  - Consider using the `react-full-screen` library to facilitate fullscreen functionality.
  - Ensure that the fullscreen toggle works smoothly and appropriately.

- [ ] **Test the enhanced caption component**:
  - Verify that all new features (playbar, control buttons, scrollbar, fullscreen mode) function correctly.
  - Ensure compatibility and responsiveness across different devices and screen sizes.

- [ ] **Gather feedback and finalize**:
  - Review the updated component with the team.
  - Make any necessary adjustments based on feedback to ensure optimal performance and user experience.
